name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Clean output directory (Unix)
        if: runner.os != 'Windows'
        run: rm -rf out

      - name: Clean output directory (Windows)
        if: runner.os == 'Windows'
        run: if (Test-Path out) { Remove-Item -Recurse -Force out }

      - name: Compile
        run: npm run compile

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test

      - name: Run tests (non-Linux)
        if: runner.os != 'Linux'
        run: npm test
